services:
  qdrant:
    image: qdrant/qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - /home/ubuntu/qdrant_storage:/qdrant/storage:z
    
  api:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - qdrant
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  telegram-bot:
    build: ./telegram
    restart: unless-stopped
    depends_on:
      - api
    volumes:
      - .:/app